# .travis.yml
language: php

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - nginx
    hosts:
      - wp.dev

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

  env:
    global:
      - COMPOSER_NO_INTERACTION=1
    matrix:
      - WP_VERSION=nightly
      - WP_VERSION=latest
      - WP_VERSION=5.8.2
      - WP_VERSION=6.3

before_install:
  # Install helper scripts
  - composer global require --prefer-dist "typisttech/travis-nginx-wordpress:^1.0.0"
  - export PATH=$HOME/.composer/vendor/bin:$PATH
  - tnw-install-nginx
  - tnw-install-wordpress
  - tnw-prepare-codeception

install:
  # Build the test suites
  - cd $TRAVIS_BUILD_DIR
  - composer install -n --prefer-dist
  - vendor/bin/codecept build -n

script:
  # Run the tests
  - cd $TRAVIS_BUILD_DIR
  - vendor/bin/codecept run -n --coverage --coverage-xml

after_script:
  - tnw-upload-coverage-to-scrutinizer
  - tnw-upload-coverage-to-codecov